name: Tests

on:
  pull_request:
  push:
    branches:
      - main

env:
  DB_NAME: oxtr_test
  DB_USERNAME: oxtr
  DB_PASSWORD: oxtr_pass

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-22.04
    services:
      db:
        image: postgres:12
        ports:
        - 5432:5432
        env:
          POSTGRES_DB: $DB_NAME
          POSTGRES_USER: $DB_USERNAME
          POSTGRES_PASSWORD: $DB_PASSWORD
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Run Postgresql Tests
        run: |
          db=postgresql bundle exec rake test
    lint:
      - uses: actions/checkout@v3
      - name: Run rubocop
        run: |
          bundle exec rubocop ${{ github.event.pull_request.base.sha }} ${{ github.sha }}
